name: Bug Report
description: Report a bug in secure-role-guard
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of secure-role-guard are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which part of the package is affected?
      options:
        - Core (defineRoles, canUser)
        - React (PermissionProvider, hooks, components)
        - Express adapter
        - Next.js adapter
        - TypeScript types
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong?
      placeholder: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Define roles with...
        2. Call canUser with...
        3. Expected result: ...
        4. Actual result: ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - Node.js version:
        - React version:
        - Framework (Next.js, Vite, etc.):
        - TypeScript version:
    validations:
      required: false
